target_column: "is_fraud"
to_feature_store: True
test_fraction: 0.3
random_state: 2021
run_name: "fraud_project"
use_feature_selection: True
feature_selection: "weighted"

# Detailed feature selection parameters
feature_selection_params:
  k_best_features: 10  # Number of features to select using statistical tests
  n_features_to_select: 10  # Number of features to select using RFE
  combination_method: "weighted"  # Options are "union", "intersection", "weighted"
  top_n_features: 10  # Number of top features to select when using weighted method
  correlation_threshold: 0.7  # Threshold for high correlation

# Model selection experiment
mlflow_model_selection_experiment: "fraud_project_model_selection"

# Model parameters
model_name: "fraud"
baseline_model_params:
  n_estimators: 100
  max_depth: 6
  max_features: 20
  random_state: 2021

# Champion model path
champion_model_path: "data/06_models/champion_model.pkl"

# Features before preprocessing
id_features:
- cc_num
- trans_num

target_feature:
- is_fraud

categorical_features:
  - merchant
  - category
  - first
  - last
  - gender
  - street
  - city
  - state
  - zip
  - job
  - merch_zipcode

categorical_features_low_cardinality:
  - category
  - gender

categorical_features_high_cardinality:
  - merchant
  - first
  - last
  - street
  - city
  - state
  - zip
  - job
  - merch_zipcode

numerical_features:
  - amt
  - lat
  - long
  - city_pop
  - age
  - merch_lat
  - merch_long

temporal_features:
- datetime

encoding:
  low_cardinality: onehot
  high_cardinality: frequency

scaling: standard