optuna_search:
  n_trials: 30
  # timeout: 600
  direction: "maximize"

  search_spaces:

    LogisticRegression:
      C: {type: "float", low: 0.001, high: 10.0, log: true}
      penalty: {type: "categorical", choices: ["l2"]}
      solver: {type: "categorical", choices: ["lbfgs", "saga"]}

    DecisionTreeClassifier:
      max_depth: {type: "int", low: 5, high: 20}
      min_samples_split: {type: "int", low: 2, high: 10}
      min_samples_leaf: {type: "int", low: 1, high: 5}
      
    RandomForestClassifier:
      n_estimators: {type: "int", low: 100, high: 300}
      max_depth: {type: "int", low: 5, high: 20}
      max_features: {type: "float", low: 0.3, high: 1.0}

    GradientBoostingClassifier:
      n_estimators: {type: "int", low: 100, high: 300}
      max_depth: {type: "int", low: 5, high: 20}
      learning_rate: {type: "float", low: 0.01, high: 0.3}
      subsample: {type: "float", low: 0.5, high: 1.0}

    # ExtraTreesClassifier:
    #   n_estimators: {type: "int", low: 100, high: 300}
    #   max_depth: {type: "int", low: 5, high: 20}
    #   max_features: {type: "float", low: 0.3, high: 1.0}

    XGBoostClassifier:
      n_estimators: {type: "int", low: 100, high: 300}
      max_depth: {type: "int", low: 5, high: 20}
      learning_rate: {type: "float", low: 0.01, high: 0.3}
      subsample: {type: "float", low: 0.5, high: 1.0}