target_column: "is_fraud"
to_feature_store: True
test_fraction: 0.3
random_state: 2021
run_name: "fraud_project"
use_feature_selection: True  # <- changed this
feature_selection: "weighted"  # <- changed this

# Detailed feature selection parameters
feature_selection_params:
  k_best_features: 15  # Number of features to select using statistical tests
  n_features_to_select: 15  # Number of features to select using RFE
  combination_method: "weighted"  # Options are "union", "intersection", "weighted"
  top_n_features: 20  # Number of top features to select when using weighted method
  correlation_threshold: 0.7  # Threshold for high correlation

model_name: "fraud"
baseline_model_params:
  n_estimators: 100
  max_depth: 6
  max_features: 20
  random_state: 2021