target_column: "is_fraud"
to_feature_store: True
test_fraction: 0.3
random_state: 2021
run_name: "fraud_project"
use_feature_selection: False
feature_selection: "rfe"
model_name: "fraud"
baseline_model_params:
  n_estimators: 100
  max_depth: 6
  max_features: 20
  random_state: 2021